"""Add ai model field in User

Revision ID: 0cc90c9489ad
Revises: b01696b0eff4
Create Date: 2024-12-30 20:00:46.630626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc90c9489ad'
down_revision: Union[str, None] = 'b01696b0eff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'model')
    # ### end Alembic commands ###
