"""Update user ID to BigInteger

Revision ID: 1803f4234c60
Revises: 84a17e51af56
Create Date: 2024-12-28 18:12:17.108132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1803f4234c60'
down_revision: Union[str, None] = '84a17e51af56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'user_id', existing_type=sa.Integer(), type_=sa.BigInteger())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
