"""Add settings to user

Revision ID: 30e171d6ad0d
Revises: 4ab963fa3e5f
Create Date: 2025-03-05 14:18:24.111828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30e171d6ad0d'
down_revision: Union[str, None] = '4ab963fa3e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'settings')
    # ### end Alembic commands ###
