"""Add audio to msg

Revision ID: 4ab963fa3e5f
Revises: 43e7317e104a
Create Date: 2025-02-19 17:37:08.816996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab963fa3e5f'
down_revision: Union[str, None] = '43e7317e104a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('audio_file_id', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('audio_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'audio_metadata')
    op.drop_column('messages', 'audio_file_id')
    # ### end Alembic commands ###
