"""Add img info

Revision ID: 82883e7854fd
Revises: b8ee20c45a1a
Create Date: 2025-01-22 22:29:09.335384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82883e7854fd'
down_revision: Union[str, None] = 'b8ee20c45a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('image_file_id', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('image_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'image_metadata')
    op.drop_column('messages', 'image_file_id')
    # ### end Alembic commands ###
